In [1]:
print("welcome to ai/ml")

welcome to ai/ml

In [2]:
def greet():
  print('Welcome to python')

In [3]:
greet()

Welcome to python

Write a function to check a given number is odd or even
pass number as an argument to the function

In [4]:
def evenOrOdd(num):
  if (num%2==0):
    print(num," is even")
  else:
    print(num," is odd")

Write shopping function to calculate
discount and amount to pay as per the given details
purchase_amt<=10000 rate=10%
purchase_amt>10000 and purchase_amt<=20000 rate=20%
purchase_amt>20000 rate = 25%
def shopping(purchase_amt)

In [6]:
def shopping(purchase_amt):
  if (purchase_amt<=10000):
    rate=.1
  elif(purchase_amt>10000 and purchase_amt<=20000):
    rate=.2
  else:
    rate=.25
  discount = purchase_amt*rate
  net_amt = purchase_amt-discount
  print(" net amount to pay ",net_amt)
  print(" discount is ",discount)

In [7]:
shopping(10000)

 net amount to pay  9000.0
 discount is  1000.0

In [5]:
evenOrOdd(11)

11  is odd

"""
List
1.Create marks empty list to store marks of students for
a subject. Max marks is 25
2. You can add marks for 5 students
3. Display marks of all students
4. Find total marks of all students
5. Find the average marks
6. Find the count of marks <15

"""
marks = []
marks.append(10)
marks.append(15)
marks.append(25)
marks.append(12)
marks.append(13)
print("loop")
total = 0
cnt=0
for mark in marks:
  print(mark)
  total = total +mark
  if (mark <15):
    cnt = cnt+1
print("total ",total)
print("average ",total/len(marks))
print("count <15 ",cnt)

In [16]:
"""
dictionary
create a dictionary of top economies
"""
topeconomy = {
              "country":["USA","CHINA","GERMANY","JAPAN","INDIA"],
              "GDP":[27,18,4.7,4.2,4.1],
              "RANK":[1,2,3,4,5]
              }
print(topeconomy)
print("gdp",topeconomy["GDP"])
print("keys ",topeconomy.keys())
print("values ",topeconomy.values())
for k,v in topeconomy.items():
  print("key = ",k, " value = ",v)

{'country': ['USA', 'CHINA', 'GERMANY', 'JAPAN', 'INDIA'], 'GDP': [27, 18, 4.7, 4.2, 4.1], 'RANK': [1, 2, 3, 4, 5]}
gdp [27, 18, 4.7, 4.2, 4.1]
keys  dict_keys(['country', 'GDP', 'RANK'])
values  dict_values([['USA', 'CHINA', 'GERMANY', 'JAPAN', 'INDIA'], [27, 18, 4.7, 4.2, 4.1], [1, 2, 3, 4, 5]])
key =  country  value =  ['USA', 'CHINA', 'GERMANY', 'JAPAN', 'INDIA']
key =  GDP  value =  [27, 18, 4.7, 4.2, 4.1]
key =  RANK  value =  [1, 2, 3, 4, 5]

In [13]:
print("dictionary")
telephonedict = {9845547471:"raghu",9845547471:"rakesh"}
telephonedict

dictionary

{9845547471: 'rakesh'}

In [17]:
"""
class and object
"""
class Product():
  def __init__(self,code,name,supplier,price,rating=None):
    self.code = code
    self.name = name
    self.supplier = supplier
    self.price = price
  def information(self):
    print("code : ",self.code," name : ",self.name, " price ",self.price)

In [18]:
laptop = Product(1,"HP gen 11","HP",75000)
print(laptop.information())
mobile = Product(2,"Nokia Smart","Nokia",35000)
print(mobile.information())

code :  1  name :  HP gen 11  price  75000
None
code :  2  name :  Nokia Smart  price  35000
None